owner: chronwire
repo: chronwire-upptime

sites:
  - name: chronwire
    url: https://chronwire.com
  - name: chronwire (API)
    url: https://chronwire.com/api/v1/tags/top?search=""

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /chronewire-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Chronwire Upptime
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Chronwire
      href: https://chronwire.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - bluenote10
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
